build fix for "m68knommu: introduce little-endian bitops"
The little-endian bitops patch series broke the build on m68knommu.

lib/find_next_bit.c:190: error: conflicting types for 'find_next_zero_le_bit'
/home/mita/scm/linux-2.6/arch/m68k/include/asm/bitops_no.h:286: error: previous
definition of 'find_next_zero_le_bit' was here

Because m68knommu selects CONFIG_GENERIC_FIND_NEXT_BIT, it redefines
find_next_zero_le_bit() in lib/find_next_bit.c.

Previous patch introduced CONFIG_GENERIC_FIND_LE_BIT to tell whether to
use generic implementation of find_*_le_bit() in lib/find_next_bit.c or not.

Don't select CONFIG_GENERIC_FIND_LE_BIT to fix build failure on m68knommu.

Signed-off-by: Akinobu Mita <akinobu.mita@gmail.com>
Cc: Greg Ungerer <gerg@uclinux.org>
Cc: Arnd Bergmann <arnd@arndb.de>